### ISSUE TITLE
Custom font is not working

### ISSUE THREAD

**Issue by oceandrama** [chakra-ui/pro-theme#2]
I created repo by manual in README and set up [custom font](https://github.com/chakra-ui/pro-theme#using-a-different-font)
https://stackblitz.com/edit/stackblitz-starters-bsfhuj?file=src%2FApp.tsx

But all components are still using `"Open Sans Variable", -apple-system, system-ui, sans-serif` font
![image](https://github.com/chakra-ui/pro-theme/assets/23439079/c65c1817-0bba-4f95-ba50-7700fafd7709)

It's happened because `proTheme` is added after our custom font configuration and overrides it
`chakra-ui` is also has [`isChakraTheme`](https://github.com/chakra-ui/chakra-ui/blob/00a06704e5ba609f5b8f4787873dd7c72d56636e/packages/components/theme/src/utils/is-chakra-theme.ts) function that returns `false` for `proTheme`, so it's overrides previous options

**Comment by cschroeter** [comment]
Thanks for taking your time to report the issue. We've updated the docs to explain the correct way to set a custom font. 

```mdx
## Setting up the Pro Theme

Setting up the Pro Theme is a straightforward process.

### 1. Import Required Themes

Firstly, you'll need to import the `theme` from the pro theme package nd the `extendTheme` function provided by Chakra UI. Use the following code snippet:

```typescript
import { theme } from '@chakra-ui/pro-theme'
import { extendTheme, ChakraProvider } from '@chakra-ui/react'
```

### 2. Create the Extended Theme

Next, create a new theme that combines the Pro Theme with your custom settings.

```javascript
const proTheme = extendTheme(theme)
const extendedConfig = {
  colors: { ...proTheme.colors, brand: proTheme.colors.teal },
}
const myTheme = extendTheme(extendedConfig, proTheme)
```

### 3. Integrate your Theme in Your Application

Finally, wrap your application within the `ChakraProvider` and apply the custom theme.

```javascript
return (
  <ChakraProvider theme={myTheme}>
    <App />
  </ChakraProvider>
)
```
